const regs = @import("rp2040_ras");

pub const SIO_GPIO = enum {
    GPIO0,
    GPIO1,
    GPIO2,
    GPIO3,
    GPIO4,
    GPIO5,
    GPIO6,
    GPIO7,
    GPIO8,
    GPIO9,
    GPIO10,
    GPIO11,
    GPIO12,
    GPIO13,
    GPIO14,
    GPIO15,
    GPIO16,
    GPIO17,
    GPIO18,
    GPIO19,
    GPIO20,
    GPIO21,
    GPIO22,
    GPIO23,
    GPIO24,
    GPIO25,
    GPIO26,
    GPIO27,
    GPIO28,
    GPIO29,
};

pub fn set_output_enable(gpio: SIO_GPIO) void {
    switch (gpio) {
        SIO_GPIO.GPIO0 => regs.SIO.GPIO_OE_SET.write_raw(1 << 0),
        SIO_GPIO.GPIO1 => regs.SIO.GPIO_OE_SET.write_raw(1 << 1),
        SIO_GPIO.GPIO2 => regs.SIO.GPIO_OE_SET.write_raw(1 << 2),
        SIO_GPIO.GPIO3 => regs.SIO.GPIO_OE_SET.write_raw(1 << 3),
        SIO_GPIO.GPIO4 => regs.SIO.GPIO_OE_SET.write_raw(1 << 4),
        SIO_GPIO.GPIO5 => regs.SIO.GPIO_OE_SET.write_raw(1 << 5),
        SIO_GPIO.GPIO6 => regs.SIO.GPIO_OE_SET.write_raw(1 << 6),
        SIO_GPIO.GPIO7 => regs.SIO.GPIO_OE_SET.write_raw(1 << 7),
        SIO_GPIO.GPIO8 => regs.SIO.GPIO_OE_SET.write_raw(1 << 8),
        SIO_GPIO.GPIO9 => regs.SIO.GPIO_OE_SET.write_raw(1 << 9),
        SIO_GPIO.GPIO10 => regs.SIO.GPIO_OE_SET.write_raw(1 << 10),
        SIO_GPIO.GPIO11 => regs.SIO.GPIO_OE_SET.write_raw(1 << 11),
        SIO_GPIO.GPIO12 => regs.SIO.GPIO_OE_SET.write_raw(1 << 12),
        SIO_GPIO.GPIO13 => regs.SIO.GPIO_OE_SET.write_raw(1 << 13),
        SIO_GPIO.GPIO14 => regs.SIO.GPIO_OE_SET.write_raw(1 << 14),
        SIO_GPIO.GPIO15 => regs.SIO.GPIO_OE_SET.write_raw(1 << 15),
        SIO_GPIO.GPIO16 => regs.SIO.GPIO_OE_SET.write_raw(1 << 16),
        SIO_GPIO.GPIO17 => regs.SIO.GPIO_OE_SET.write_raw(1 << 17),
        SIO_GPIO.GPIO18 => regs.SIO.GPIO_OE_SET.write_raw(1 << 18),
        SIO_GPIO.GPIO19 => regs.SIO.GPIO_OE_SET.write_raw(1 << 19),
        SIO_GPIO.GPIO20 => regs.SIO.GPIO_OE_SET.write_raw(1 << 20),
        SIO_GPIO.GPIO21 => regs.SIO.GPIO_OE_SET.write_raw(1 << 21),
        SIO_GPIO.GPIO22 => regs.SIO.GPIO_OE_SET.write_raw(1 << 22),
        SIO_GPIO.GPIO23 => regs.SIO.GPIO_OE_SET.write_raw(1 << 23),
        SIO_GPIO.GPIO24 => regs.SIO.GPIO_OE_SET.write_raw(1 << 24),
        SIO_GPIO.GPIO25 => regs.SIO.GPIO_OE_SET.write_raw(1 << 25),
        SIO_GPIO.GPIO26 => regs.SIO.GPIO_OE_SET.write_raw(1 << 26),
        SIO_GPIO.GPIO27 => regs.SIO.GPIO_OE_SET.write_raw(1 << 27),
        SIO_GPIO.GPIO28 => regs.SIO.GPIO_OE_SET.write_raw(1 << 28),
        SIO_GPIO.GPIO29 => regs.SIO.GPIO_OE_SET.write_raw(1 << 29),
    }
}

pub fn set_output(gpio: SIO_GPIO) void {
    switch (gpio) {
        SIO_GPIO.GPIO0 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 0),
        SIO_GPIO.GPIO1 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 1),
        SIO_GPIO.GPIO2 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 2),
        SIO_GPIO.GPIO3 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 3),
        SIO_GPIO.GPIO4 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 4),
        SIO_GPIO.GPIO5 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 5),
        SIO_GPIO.GPIO6 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 6),
        SIO_GPIO.GPIO7 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 7),
        SIO_GPIO.GPIO8 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 8),
        SIO_GPIO.GPIO9 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 9),
        SIO_GPIO.GPIO10 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 10),
        SIO_GPIO.GPIO11 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 11),
        SIO_GPIO.GPIO12 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 12),
        SIO_GPIO.GPIO13 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 13),
        SIO_GPIO.GPIO14 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 14),
        SIO_GPIO.GPIO15 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 15),
        SIO_GPIO.GPIO16 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 16),
        SIO_GPIO.GPIO17 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 17),
        SIO_GPIO.GPIO18 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 18),
        SIO_GPIO.GPIO19 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 19),
        SIO_GPIO.GPIO20 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 20),
        SIO_GPIO.GPIO21 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 21),
        SIO_GPIO.GPIO22 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 22),
        SIO_GPIO.GPIO23 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 23),
        SIO_GPIO.GPIO24 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 24),
        SIO_GPIO.GPIO25 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 25),
        SIO_GPIO.GPIO26 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 26),
        SIO_GPIO.GPIO27 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 27),
        SIO_GPIO.GPIO28 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 28),
        SIO_GPIO.GPIO29 => regs.SIO.GPIO_OUT_SET.write_raw(1 << 29),
    }
}

pub fn clear_output(gpio: SIO_GPIO) void {
    switch (gpio) {
        SIO_GPIO.GPIO0 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 0),
        SIO_GPIO.GPIO1 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 1),
        SIO_GPIO.GPIO2 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 2),
        SIO_GPIO.GPIO3 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 3),
        SIO_GPIO.GPIO4 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 4),
        SIO_GPIO.GPIO5 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 5),
        SIO_GPIO.GPIO6 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 6),
        SIO_GPIO.GPIO7 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 7),
        SIO_GPIO.GPIO8 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 8),
        SIO_GPIO.GPIO9 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 9),
        SIO_GPIO.GPIO10 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 10),
        SIO_GPIO.GPIO11 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 11),
        SIO_GPIO.GPIO12 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 12),
        SIO_GPIO.GPIO13 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 13),
        SIO_GPIO.GPIO14 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 14),
        SIO_GPIO.GPIO15 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 15),
        SIO_GPIO.GPIO16 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 16),
        SIO_GPIO.GPIO17 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 17),
        SIO_GPIO.GPIO18 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 18),
        SIO_GPIO.GPIO19 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 19),
        SIO_GPIO.GPIO20 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 20),
        SIO_GPIO.GPIO21 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 21),
        SIO_GPIO.GPIO22 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 22),
        SIO_GPIO.GPIO23 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 23),
        SIO_GPIO.GPIO24 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 24),
        SIO_GPIO.GPIO25 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 25),
        SIO_GPIO.GPIO26 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 26),
        SIO_GPIO.GPIO27 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 27),
        SIO_GPIO.GPIO28 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 28),
        SIO_GPIO.GPIO29 => regs.SIO.GPIO_OUT_CLR.write_raw(1 << 29),
    }
}

pub fn xor_output(gpio: SIO_GPIO) void {
    switch (gpio) {
        SIO_GPIO.GPIO0 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 0),
        SIO_GPIO.GPIO1 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 1),
        SIO_GPIO.GPIO2 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 2),
        SIO_GPIO.GPIO3 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 3),
        SIO_GPIO.GPIO4 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 4),
        SIO_GPIO.GPIO5 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 5),
        SIO_GPIO.GPIO6 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 6),
        SIO_GPIO.GPIO7 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 7),
        SIO_GPIO.GPIO8 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 8),
        SIO_GPIO.GPIO9 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 9),
        SIO_GPIO.GPIO10 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 10),
        SIO_GPIO.GPIO11 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 11),
        SIO_GPIO.GPIO12 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 12),
        SIO_GPIO.GPIO13 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 13),
        SIO_GPIO.GPIO14 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 14),
        SIO_GPIO.GPIO15 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 15),
        SIO_GPIO.GPIO16 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 16),
        SIO_GPIO.GPIO17 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 17),
        SIO_GPIO.GPIO18 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 18),
        SIO_GPIO.GPIO19 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 19),
        SIO_GPIO.GPIO20 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 20),
        SIO_GPIO.GPIO21 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 21),
        SIO_GPIO.GPIO22 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 22),
        SIO_GPIO.GPIO23 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 23),
        SIO_GPIO.GPIO24 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 24),
        SIO_GPIO.GPIO25 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 25),
        SIO_GPIO.GPIO26 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 26),
        SIO_GPIO.GPIO27 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 27),
        SIO_GPIO.GPIO28 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 28),
        SIO_GPIO.GPIO29 => regs.SIO.GPIO_OUT_XOR.write_raw(1 << 29),
    }
}
